
<div class="plain-box"><h2 class="first"></h2> 
 
<div style="text-align:center;margin-bottom:1em;margin-top:1em">
<a href="http://www.gramene.org"><img src="/i/gramene_logo.png"></a><br/>
<a href="http://www.ebi.ac.uk"><img src="http://www.ebi.ac.uk/inc/images/ebilogohelp.gif" style="height:50px"></a>
</div>

<p> 
This work is a joint project between <a
href="http://www.ensemblgenomes.org">EnsemblGenomes</a> at the <a
href="http://www.ebi.ac.uk">European Bioinformatics Institute</a> and
the group of <a href="http://www.warelab.org">Doreen Ware</a> at the
<a href="http://www.cshl.org">Cold Spring Harbor Laboratory</a>, who
have developed the <a href="http://www.gramene.org">Gramene</a>
database, a resource for plant comparative genomics based on Ensembl
technology.  A common set of databases are available through
EnsemblGenomes and Gramene, and the two groups are collaborating on the
integration of content, quality control and the development of new
features.
</p>
</div>
