<div class="plain-box"><h2>Acknowledgements</h2>

<p>Ensembl Plants is a joint project of the <a href="http://www.ebi.ac.uk">European Bioinformatics Institute</a> and the group of <a href="http://www.cshl.edu/public/SCIENCE/ware.html">Doreen Ware</a> at the <a href="http://www.cshl.org">Cold Spring Harbor Laboratory</a>, who have developed the <a href="http://www.gramene.org">Gramene</a> database [1,2], a resource for plant comparative genomics based on Ensembl technology [3,4]. A common set of databases are available through Ensembl Plants and Gramene, and the two groups are collaborating on the integration of content, quality control and the development of new features.</p>

<p class="rtecenter"><a href="http://www.ebi.ac.uk"><img alt="EBI logo" class="logo" src="http://www.ebi.ac.uk/inc/images/ebilogohelp.gif" style="height:30px; margin-left:6px; margin-right:6px" /></a><a href="http://www.cshl.org"><img alt="CSHL logo" class="logo" src="/img/cshllogostandardrgb.png" style="height:30px; margin-left:6px; margin-right:6px" /></a><a href="http://www.gramene.org"><img alt="Gramene logo" class="logo" src="http://www.gramene.org/sites/default/files/gramene_logo.png" style="height:30px; margin-left:6px; margin-right:6px" /></a></p>

<h3>References</h3>

<ol><li>Youens-Clark, K., et al., Gramene database in 2010: updates and extensions. Nucleic Acids Res. 2010. 39:D1085-94<br /><a href="http://europepmc.org/abstract/MED/21076153">PubMed ID: 21076153</a></li>
	<li>Monaco MK., et al., Gramene 2013: comparative plant genomics resources. Nucleic Acids Res. 2014. 42:D1193-9.<br /><a href="http://europepmc.org/abstract/MED/24217918">PubMed ID: 24217918</a></li>
	<li>Hubbard, T., et al., The Ensembl genome database project. Nucleic Acids Res. 2002. 30:38-41<br /><a href="http://europepmc.org/abstract/MED/11752248">PubMed ID: 11752248</a></li>
	<li>Kersey PJ., et al., Ensembl Genomes 2013: scaling up access to genome-wide data. Nucleic Acids Res. 2014. 42:D546-52.<br /><a href="http://europepmc.org/abstract/MED/24163254">PubMed ID: 24163254</a></li></ol>
</div>