
<div class="plain-box"><h2 class="first"></h2> 
 
<div style="text-align:center;margin-bottom:1em;margin-top:1em">
<a href="http://www.gramene.org"><img src="/i/gramene_logo.png"></a><br/>
<a href="http://www.omap.org/resources.html"><img src="http://www.omap.org/img/banner.gif" style="height:50px"></a>
<a href="http://www.ebi.ac.uk"><img src="http://www.ebi.ac.uk/inc/images/ebilogohelp.gif" style="height:50px"></a>
</div>

<p> 
This work is a joint project between <a href="http://www.omap.org/resources.html">OMAP</a> at the 
<a href"http://www.genome.arizona.edu/"> Arizona Genome Institute </a> and
the group of <a href="http://www.warelab.org">Doreen Ware</a> at the
<a href="http://www.cshl.org">Cold Spring Harbor Laboratory</a>, who
have developed the <a href="http://www.gramene.org">Gramene</a>
database, a resource for plant comparative genomics based on Ensembl
technology at the <a href="http://www.ebi.ac.uk">European Bioinformatics Institute</a>.
In addition to genomes sequenced and assemblied at AGI, the International OMAP collaboration brought additional
Oryza whole genomes sequenced and assemblied by groups in Australia, China and France. A uniform set of baseline annotations
were performed on these genomes such as MAKER-P gene annotation, repeats annotations, additional comparative analyses were
also conducted on whole genome scale both on protein level and DNA level by Gramene.
</p>
</div>
