<div class="plain-box"><h2>New Bread Wheat Genome Assembly</h2>

<p>A new genome assembly of <a href="http://ensembl.gramene.org/Triticum_aestivum"><em>Triticum aestivum</em></a> cv. Chinese Spring is now available in Gramene and Ensembl Plants. The assembly (TGACv1) and it's accompanying annotation was produced by the <a href="http://www.earlham.ac.uk/">Earlham Institute</a>, formerly The Centre for Genome Analysis (TGAC), as part of the<!--nbsp--> <!--nbsp--><a href="http://www.wheatgenome.org.uk/">Triticeae Genomics for Sustainable Agriculture</a><!--nbsp--> <!--nbsp-->project.</p>

<p>The assembly has a scaffold N50 of 88 Kbp and a total length of 13.4 Gbp in contigs greater than 500 bp (<a href="http://ensembl.gramene.org/Triticum_aestivum/Info/Annotation#assembly">read more</a>). The gene model annotation consists of 217,907<!--nbsp--> <!--nbsp-->loci and 273,739 transcripts. A total of 104,09<!--nbsp--> <!--nbsp-->protein coding genes (154,798 transcripts) and 10,156 long ncRNAs have been annotated with high confidence (<a href="http://ensembl.gramene.org/Triticum_aestivum/Info/Annotation#annotation">read more</a>). Approximately 99,000 genes (99% of the total) annotated on the previous IWGSC CSS assembly (MIPS) have been mapped to the new assembly.</p>

<p>The Axiom 35k and 820k SNP marker sets have been<!--nbsp--> <!--nbsp-->provided by <a href="http://www.cerealsdb.uk.net/cerealgenomics/CerealsDB/indexNEW.php">CerealsDB</a><!--nbsp--> <!--nbsp-->and located on the new assembly (<a href="http://ensembl.gramene.org/Triticum_aestivum/Info/Annotation#variation">read more</a>).</p>

<p><!--nbsp--> <!--nbsp--></p></div>
