<h2 id="features">Featured content</h2>

<li>This release of Gramene includes the first unified assembly IGRSP1/MSU7 of <a href="/Oryza_sativa/Info/Index"><i>Oryza sativa</i></a> japonica by the <a href="http://rapdb.dna.affrc.go.jp/">Rice Annotation Project Database (RAP-DB)</a> / <a href="http://rgp.dna.affrc.go.jp/IRGSP/">International Rice Genome Sequencing Project (IRGSP)</a> and the <a href="http://rice.plantbiology.msu.edu/">MSU Rice Genome Annotation Project (MSU)</a>.</li>

<li>Also featured is the first draft of the <a href="/Triticum_aestivum/Info/Index">bread wheat genome</a> from the <a href="http://www.wheatgenome.org/">International Wheat Genome Sequencing Project IWGSC</a>.</li>

<p>

<h3>References</h3>

<p>
<a href="http://www.ncbi.nlm.nih.gov/pubmed/23192148">Analysis of the bread wheat genome using whole-genome shotgun sequencing</a>. Brenchley R, Spannagl M, Pfeifer M, Barker GL, D'Amore R, Allen AM, McKenzie N, Kramer M, Kerhornou A, Bolser D, Kay S, Waite D, Trick M, Bancroft I, Gu Y, Huo N, Luo MC, Sehgal S, Gill B, Kianian S, Anderson O, Kersey P, Dvorak J, McCombie WR, Hall A, Mayer KF, Edwards KJ, Bevan MW, Hall N. (2012). Nature 491(7426):705-10.
</p>

