<div class="plain-box"><h2>
<h2 id="features">Featured content</h2>

This release of version 2 includes the updated assembly and annotation of Oryza meridionalis <em><a title="Oryza meridionalis in OGE" href="/Oryza_meridionalis">Oryza meridionalis</a></em> and updated ncRNA annotations for Oryza meridionalis, Oryza rufipgon, Oryza glumaepatula, Leersia perrieri. It also added RNAseq expression profile from root, leaf and panicle for 10 of the OGE whole genomes, and nuclear organelle insertion annotations provided by Christos in Doreen Ware's lab. 

<p>
<p>
In addition blast search tool was installed and integrated with the genome browser, which use ensembl-79 infrastructure.
  
</div>
