<div class="plain-box"><h2>What's New in Release 51</h2>
<div class="info-box embedded-box float-right"><h3>Did you know...?</h3><p><a href="http://trackhubregistry.org/"><img alt="Read more" src="http://ensemblgenomes.org/sites/ensemblgenomes.org/files/field/image/thr-02.png" style="float:right; height:40px; margin:1px 5px; width:40px" title="The Track Hub Registry" /></a></p>

<p>You can search the <a href="http://trackhubregistry.org/">Track Hub Registry</a> to find more than 900 public RNA-Seq studies aligned to plants (<a href="http://ensemblgenomes.org/info/access/public-track-hubs">read more on the Ensembl Genomes site</a>).</p></div>
<ul><li>New genomes
	<ul><li><a href="http://ensembl.gramene.org/Beta_vulgaris"><em>Beta vulgaris</em></a></li>
		<li><a href="http://ensembl.gramene.org/Brassica_napus"><em>Brassica napus</em></a></li>
		<li><a href="http://ensembl.gramene.org/Trifolium_pratense"><em>Trifolium pratense</em></a></li>
		<li>Transfer of two Rhodophyta genomes from Ensembl Protists, <a href="http://ensembl.gramene.org/Galdieria_sulphuraria"><em>Galdieria sulphuraria</em></a> and <a href="http://ensembl.gramene.org/Chondrus_crispus"><em>Chondrus crispus</em></a></li></ul>
	</li>
<ul><li>Updated software
    <ul><li>Updated to <a href="http://www.ensembl.info/blog/2016/07/19/ensembl-85-has-been-released">Ensembl 85 software</a></li></ul>
<li>Updated genomes
	<ul><li><a href="http://ensembl.gramene.org/Triticum_aestivum"><em>Triticum aestivum</em></a></li>
		<li><a href="http://ensembl.gramene.org/Zea_mays"><em>Zea mays</em> (RefGenV4)</a></li></ul>
	</li>
	<li>Updated data
	<ul><li>Updated protein features from InterPro</li>
		<li>Updated peptide comparative genomics</li>
		<li>Updated BioMarts</li></ul>
	</li></ul>
</div>
