<div class="plain-box"><h2>What's New in Release 45</h2>
<div class="info-box embedded-box float-right"><h3>Did you know...?</h3><p><img src="/img/brachyvsbarley-trans.png" alt="Stats" title="Stats" width="50" height="50" style="float: right; padding: 0px 0px 5px 5px;" />We now generate stats for all our whole genome alignments (e.g. for <a href="/mlss.html?mlss=9046">Brachypodium vs. Barley</a>. The full set can be browsed on the <a href="/compara_analyses.html">genomic alignments</a> page.</p></div><ul><li>Updated genomes</li>
<ul><li><a href="/Medicago_truncatula"><em>Medicago truncatula</em></a><!--nbsp--> <!--nbsp-->latest assembly and gene set.</li>
<li><a href="/Oryza_meridionalis"><em>Oryza meridionalis</em></a><!--nbsp--> <!--nbsp-->latest assembly and gene set.</li>
</ul>
</li>
<li><span>New data</span>
<ul><li><span>Whole genome alignments between Triticeae genomes using <a href="http://seqanswers.com/wiki/ATAC">ATAC</a> between:</span>
<ul><li>The <em>Triticum aestivum</em> (bread wheat) component genomes (A, B and D - <a href="http://plants.ensembl.org/mlss.html?mlss=9413">stats</a>).</li>
<li><em>T. urartu vs.</em> the bread wheat A component genome (<a href="http://plants.ensembl.org/mlss.html?mlss=9414">stats</a>).</li>
<li><em>Aegilops tauschii vs.</em> the bread wheat D component genome (<a href="http://plants.ensembl.org/mlss.html?mlss=9415">stats</a>.</li>
<li><span><em>T. urartu vs. A. tauschii</em> (<a href="http://plants.ensembl.org/mlss.html?mlss=9409">stats</a>).</span></li>
<li><span><em>Hordeum vulgare vs. T. aestivum</em> (<a href="http://plants.ensembl.org/mlss.html?mlss=9410">stats</a>), <em>T. urartu</em> (<a href="http://plants.ensembl.org/mlss.html?mlss=9411">stats</a>) and <em>A. tauschii</em> (<a href="http://plants.ensembl.org/mlss.html?mlss=9412">stats</a>).</li></ul>
</li>
<li><span>Whole genome alignments using LASTZ between<!--nbsp--> <!--nbsp--></span>:
<ul><li><em>Brassica oleracea</em></a><span><!--nbsp--> <!--nbsp-->and<!--nbsp--> <!--nbsp--></span><em>Arabidopsis thaliana</a></em><!--nbsp--> <!--nbsp-->(<a href="http://plants.ensembl.org/mlss.html?mlss=9385">stats</a>).</li>
<li><em>M. truncatula</em> and <em>Glycine max</em>, <em>Arabidopsis thaliana</em>, <em>Vitis vinifera</em> and <em>O. sativa</em> group Japonica.</li>
</ul>
<li>Enabled the assembly converter tool to allow conversion of tomato 2.50 onto 2.40 coordinates.</li>
<li>Synteny regions for bread wheat against <em>O. sativa</em> Japonica.</li>
<li>Two new RNA-Seq studies aligned to barley (<a href="/Hordeum_vulgare/Info/Annotation#genebuild">read more</a>).
<li>New RNA-Seq studies (leaf, root and panicle) for OGE genomes, including <em>O. barthii</em>, <em>O. brachyantha</em>, <em>O. glaberrima</em>, <em>O. glumaepatula</em>, <em>O. meridionals</em>, <em>O. nivara</em>, <em>O. punctata</em>, <em>O. rufipogon</em>, <em>O. sativa</em> Japonica and <em>Leersia perrieri</em>.
<li>New genome browser tracks for <em>Zea mays</em> (<a href="/Zea_mays/Info/Annotation#genebuild">read more</a>).</li>
<li>New browser tracks for <em>Sorghum bicolor</em> (<a href="/Sorghum_bicolor/Info/Annotation#genebuild">read more</a>).</li>
<li>New links to gene annotations from AraPort and Expression ATLAS (see for example, <a href="http://ensembl.gramene.org/Arabidopsis_thaliana/Gene/Matches?db=core;g=AT3G52430;r=3:19431371-19434403;t=AT3G52430.1"><em>pad4</em></a>).</li> 
</ul>
</li>
<li>Updated data
<ul>
<li>Updated to Ensembl 79 software.</li>
<li>Updated gene, sequence and variation BioMarts.</li>
<li>Updated BLAST software from Ensembl.</li>
<li>Peptide comparative genomics data across all species.</li>
<li>Projection of manual GO annotation from <em>Arabidopsis thaliana</em> to 1:1 orthologues in all other plant species.</li>
<li>Projection of manually assigned gene names and descriptions from <em>Arabidopsis thaliana</em> to 1:1 orthologues in all other dicotyledons species.</li>
<li>Renamed the unordered barley chromosomes.</li>
</ul>
</li></ul>
</div>
