<div class="plain-box"><h2>What's New in Release 55</h2>
<div class="info-box embedded-box float-right"><h3>Did you know...?</h3><p><a href="http://trackhubregistry.org/"><img alt="Read more" src="http://ensemblgenomes.org/sites/ensemblgenomes.org/files/field/image/thr-02.png" style="float:right; height:40px; margin:1px 5px; width:40px" title="The Track Hub Registry" /></a></p>

<p>You can search the <a href="http://trackhubregistry.org/">Track Hub Registry</a> to find more than 1,400 public RNA-Seq studies aligned to plants (<a href="http://ensemblgenomes.org/info/access/public-track-hubs">read more</a>) on the Ensembl Genomes site.</p></div>
<ul><li>New genomes</li>
        <ul><li>New genome for <a href="/Corchorus_capsularis" title="Jute in Gramene"><em>Corchorus capsularis</em></a> Jute (GCA_001974805)</li></ul>
        </li>
        <li>New data
	<ul><li>New alignment based cross references to UniProt and RefSeq across all plants</li>
	<li>New automatic ncRNA gene annotations across all plants</li>
	<li>New <a href="http://plantreactome.gramene.org">plant reactome</a> cross-references across all plants</li>
	<li>New whole genome alignments between Hordeum vulgare (barley) and 
	<ul><li><a href=/Oryza_sativa><em> Oryza sativa</em></a> <a href="/mlss.html?mlss=9557">(summarized here)</a>, and</li>
    	<li><a href=/Brachypodium_distachyon><em>Brachypodium distachyon</em></a> <a href="/mlss.html?mlss=9558">(summarized here)</a>
        </li></ul></ul>
        <li>Updated data
	<ul><li>Updated <a href="http://ensemblgenomes.org/info/data/peptide_compara">peptide comparative genomics</a> including the new Jute genome</li>
 	<li>Updated protein features using <a href="http://www.ebi.ac.uk/interpro/search/sequence-search">InterProScan</a> with version 64 of <a href="https://www.ebi.ac.uk/interpro/">InterPro</a></li>
         <li>Updated <a href="http://ensembl.gramene.org/biomart/martview">BioMart</a></li></ul>
        </li>
	<li>New web features</li>
    		<ul><li>Pathyways link on gene pages</li>
    		<li>Neighborhood conservation mode to the Homology tab of the results of <a href="http://www.gramene.org">Gramene's main search query</a></li></ul>
	<li>Updated software
    	<ul><li>Updated genome browser, database schema, Mart and API to <a href="http://ensembl.org/info/website/news.html?id=90">Ensembl 90 software</a></li></ul>
        </li></ul>
</div>
