<div class="plain-box"><h2>New wheat assembly</h2>

<p>Gramene hosts the<!--nbsp--> <!--nbsp--><a href="/Wheat">latest wheat assembly</a><!--nbsp--> <!--nbsp-->from the IWGSC (RefSeq v1.0). Current data includes:</p>

<ul><li>The IWGSC RefSeq v1.1 gene annotation.</li>
	<li>Alignment of 98,270 high confidence genes from the TGACv1 annotation.</li>
	<li>The Axiom 820K SNP Array from CerealsDB.</li>
	<li>Thr Axiom 35K SNP array from CerealsDB.</li>
	<li>EMS-induced mutations from sequenced TILLING populations (Kronos and Cadensa).</li>
	<li>Inter-Homeologous Variants (IHVs) between the A, B and D genome components.</li>
	<li>Assembly to assembly mapping and gene ID mapping to the previous TGAC v1 assembly and annotation.</li>
	<li>Whole genome alignments to rice, brachypodium and barley.</li>
	<li>The TGACv1 assembly will still be availble via the<!--nbsp--> <!--nbsp--><a href="http://oct2017-plants.ensembl.org/index.html">Ensembl Plants archive site</a>.</li></ul>
<h2>Polyploid View Enabled</h2>

<p>Polyploid view for<!--nbsp--> <!--nbsp--><a href="/Wheat">wheat</a> and Emmer Zavitan wheat (<a href="/Triticum_dicoccoides">Triticum dicoccoides</a>) has been enabled, allowing users to view alignments among multiple wheat components<!--nbsp--> <!--nbsp--><a href="/Triticum_aestivum/Location/MultiPolyploid?db=core;g=TraesCS7A02G200000;r=7A:162572423-162579126;r1=7D:161387881-161394584:1;r2=7B:123652787-123659490:1;s1=Triticum_aestivum--7D;s2=Triticum_aestivum--7B;t=TraesCS7A02G200000.1">simultaneously</a>.</p></div>
