<div class="plain-box"><h2>New barley genome</h2>

<p>A ten-nation consortium has reported the first high-quality reference genome sequence of <a href="http://plants.ensembl.org/Hordeum_vulgare" title="Hordeum vulgare in Ensembl Plants"><em>Hordeum vulgare</em></a> (barley). The barley genome was sequenced and assembled using an array of state-of- the-art methods, taking ten years. For the first time, scientists can now locate all genes precisely in the genome and analyze complex gene families that play a key role in malting and resilience.</p>

<h2>New Arabidopsis variation data from the 1001 Genomes Project</h2>

<p>We have upgraded our representation of genetic variation in <a href="http://plants.ensembl.org/Arabidopsis_thaliana" title="Arabidopsis thaliana in Ensembl Plants">Arabidopsis thaliana</a>, incorporating the full data set from the <a href="http://1001genomes.org/" title="1001genomes.org">1001 Genomes Project</a>, covering more than 10 million variant loci across 1,135 samples (<a href="http://europepmc.org/abstract/MED/27293186" title="Europe PMC">Cell 2016</a>).</p>

<h2>New bread wheat variation data</h2>

<p>A total of 80,829 variation markers from the iSelect 90k array and 13.8 million Inter-Homoeologous Variants (IHVs) have been added to the new genome assembly of <a href="http://plants.ensembl.org/Triticum_aestivum"><em>Triticum aestivum</em></a> cv. Chinese Spring produced by the <a href="http://www.earlham.ac.uk/">Earlham Institute</a>.</p>

<p>This data is viewable alongside the existing Axiom 35k and 820k SNP marker sets provided by <a href="http://www.cerealsdb.uk.net/cerealgenomics/CerealsDB/indexNEW.php">CerealsDB</a> and located on the new assembly <strong>and</strong> the publicly available EMS mutant lines from tetraploid (cv. Kronos) and hexaploid (cv. Cadenza) TILLING populations (<a href="http://plants.ensembl.org/Triticum_aestivum/Info/Annotation#variation">read more</a>).</p>

<h2>Ensembl Plants Archive Site</h2>

<p>Alongside release 32 we have launched a new <a href="http://archive.plants.ensembl.org/">archive site</a>, where we will keep selected previous releases of Ensembl Plants publicly available. The first release available on the archive site is release 31, and includes the previous assemblies for wheat and maize.</p></div>
