<div class="plain-box"><h2>Polyploid View Enabled</h2>

<p>Polyploid view for<!--nbsp--> <!--nbsp--><a href="http://ensembl.gramene.org/Triticum_aestivum/Info/Index">wheat</a><!--nbsp--> <!--nbsp-->has been enabled, allowing users to view alignments between all 3 wheat components<!--nbsp--> <!--nbsp--><a href="http://ensembl.gramene.org/Triticum_aestivum/Location/MultiPolyploid?db=core;g=TRIAE_CS42_6DL_TGACv1_526338_AA1679880;r=TGACv1_scaffold_526338_6DL:198278-201729;r1=TGACv1_scaffold_500260_6BL:98835-102286:-1;r2=TGACv1_scaffold_472311_6AL:52247-55698:1;s1=Triticum_aestivum--TGACv1_scaffold_500260_6BL;s2=Triticum_aestivum--TGACv1_scaffold_472311_6AL;t=TRIAE_CS42_6DL_TGACv1_526338_AA1679880.1">simultaneously</a>.</p>

<h2>Functional Genomics</h2>

<p>26 new and updated functional genomic databases (<a href="http://ensembl.gramene.org/Arabidopsis_thaliana/Transcript/Oligos?db=core;g=AT1G01030;r=1:8001-18000;t=AT1G01030.2">example</a> for Arabidopsis).</p>

<h2>Arabidopsis variation data from the 1001 Genomes Project</h2>

<p>The representation of genetic variation of <a href="http://ensembl.gramene.org/Arabidopsis_thaliana" title="Arabidopsis thaliana in Gramene">Arabidopsis thaliana</a> incorporates the full data set from the <a href="http://1001genomes.org/" title="1001genomes.org">1001 Genomes Project</a>, covering more than 10 million variant loci across 1,135 samples (<a href="http://europepmc.org/abstract/MED/27293186" title="Europe PMC">Cell 2016</a>).</p>

<h2>Ensembl Plants Archive Site</h2>

<p>Alongside release 32, Ensembl Plants launched a new <a href="http://archive.plants.ensembl.org/">archive site</a>, where selected previous releases of Ensembl Plants are being kept publicly available. The first release available on the archive site is release 31, and includes the previous assemblies for wheat and maize.</p></div>
