#!/usr/local/bin/perl

package rss;

use strict;
use warnings;
no warnings "uninitialized";

use EnsEMBL::Web::Document::WebPage;

my $webpage = new EnsEMBL::Web::Document::WebPage
    (
     'scriptname' => 'rss',
     'objecttype' => 'Rss',
     'outputtype' => 'none',
     'outputtype_version' => 'none',
     );

if ($webpage->has_a_problem){
    $webpage->render_error_page;
} 

else{
    my $object = $webpage->dataObjects->[0];
    $webpage->configure($object, 'configure_rss','context_menu');

    if( $object->has_problem_type('redirect')){
	$webpage->redirect($object->problem->[0]->name);
    }
    
    else {
	$webpage->render;
    }
}

1;
