<br/><h2>Gene Tree Statistics</h2>
<div style="float:left; padding:20px">
<img src="/i/96/compara.png" class="bordered">
</div>
<div>
<p><a href="/prot_tree_stats.html">Overview</a></p>
<p><a href="/prot_tree_stats.html?page=coverage">Gene tree coverage and Gene QC</a></p>
<p><a href="/prot_tree_stats.html?page=sizes">Size of gene trees</a></p>
<p><a href="/prot_tree_stats.html?page=nodes">Gene tree nodes</a></p>
</div>

