<div class="plain-box"><h2>What's New in Release 4</h2>
<ul><li>New Oryza genomes
<ul>		
<li><a href="/Oryza_indicair8"><em>Oryza sativa indica</em> XI-1B1 var. IR8</a></li>
<li><a href="/Oryza_sativair64"><em>Oryza sativa indica </em>XI-1B1 var. OsIR64</em></a></li>
<li><a href="/Oryza_sativa127742"><em>Oryza sativa indica</em> XI-1B2 var. Os127742</a></li>
<li><a href="/Oryza_sativa132424"><em>Oryza sativa indica</em> XI-2A var. Os132424</a></li>
<li><a href="/Oryza_sativa125619"><em>Oryza sativa indica</em> XI-2B var. Os125619</a></li>
<li><a href="/Oryza_sativa127564"><em>Oryza sativa indica</em> XI-3A var. Os127564</a></li>
<li><a href="/Oryza_sativa127518"><em>Oryza sativa indica</em> XI-3B1 var. Os127518</a></li>
<li><a href="/Oryza_sativa125827"><em>Oryza sativa indica</em> XI-3B2 var. Os125827</a></li>
<li><a href="/Oryza_sativamh63"><em>Oryza sativa indica</em> XI-adm var. MH63</a></li>
<li><a href="/Oryza_sativazs97"><em>Oryza sativa indica</em> XI-1A var. ZS97</a></li>

<li><a href="/Oryza_sativa128077"><em>Oryza sativa japonica</em> GJ-trop2 var. Os128077</a></li>
<li><a href="/Oryza_sativa132278"><em>Oryza sativa japonica</em> GJ-subtrp var. Os132278</a></li>
<li><a href="/Oryza_sativaazucena"><em>Oryza sativa japonica</em> GJ-trop1 var. Azucena</a></li>
<li><a href="/Oryza_aus"><em>Oryza sativa aus</em> cA1 var. N22</em></a></li>
<li><a href="/Oryza_sativa127652"><em>Oryza sativa aus </em>cA2 var. Os127652</a></li>
<li><a href="/Oryza_sativa117425"><em>Oryza sativa indica</em> cB var. Os117425</a></li>
<li><a href="/Oryza_carolina"><em>Oryza sativa japonica</em> var. Carolina</a></li>
<li><a href="/Oryza_sativakitaake"><em>Oryza sativa japonica</em> var. KitaakeX</a></li>
</ul>
</li>

<li>Updated Oryza genomes
	<ul> 
	<li><a href="/Oryza_indica"><em>Oryza sativa indica</em></a></li>
	</ul>
</li>
<li>New & updated data
<ul><li>Updated InterPro scan protein features.</li>
 <li>Updated Compara gene tree analysis, ortholog and paralog predictions. A total of 38,308 GeneTree families were constructed comprising 1,239,682 individual genes from 36 plant genomes with 1,294,888 input proteins. See more stats <a href=/prot_tree_stats.html> here</a>.	
</li>
</ul>
</div>


<!--A total of 38308 GeneTree families were constructed comprising 1239682 individual genes from 36 plant genomes with 1294888 input proteins.A total of 37,423 GeneTree families were constructed comprising 1,134,514 individual genes (1,187,461 input proteins)-->
